/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_buffalo_cse_memtool_MemUtil */

#ifndef _Included_edu_buffalo_cse_memtool_MemUtil
#define _Included_edu_buffalo_cse_memtool_MemUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_buffalo_cse_memtool_MemUtil
 * Method:    malloc
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_buffalo_cse_memtool_MemUtil_malloc
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
